### ISSUE TITLE
Not loading if there are no keywords in bibtex-file

### ISSUE THREAD

**Issue by kblumenstein** [aha01/PubViz#1]
if there are no keywords in bibtex-file pubviz is not loading.

This code at line 3880 fixes this issue

```
var fontSize;
if(params.words.length!=0){
   fontSize = d3.scale.log().domain([params.words[(params.words.length-1)].size ,params.words[0].size])
                                             .range( [15, 50] )
                                             .clamp( true );
}else{
    fontSize = 12;
}
```

**Comment by aha01** [comment]
thank you for your contribution which is now included in the pubviz file. Now there should be no loading problems even if no keywords | years | authors | types are in the bibtex file.
