### ISSUE TITLE
Display error when bibtex file not found

### ISSUE THREAD

**Issue by aevoid** [aha01/PubViz#6]
It would be cool to get an error message, when the provided bibtex file could not be loaded (e.g. URL incorrect, ...).

Just append a  .fail(function() {}); to https://github.com/aha01/PubViz/blob/master/src/pubvis.js#L22-28 as proposed in http://api.jquery.com/jquery.get/ .

**Comment by aha01** [comment]
Thank you for your for your helpful clues. Now, an error message will show up if the bibtex file cannot be found. Please run an update to the actual code on GitHub.
